// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLmXOw2rCz7H39uAKehWoSko8GaQTyPYA',
    appId: '1:140072372671:web:fa0c5916910c182d6a390a',
    messagingSenderId: '140072372671',
    projectId: 'nnd-fr-translator2',
    authDomain: 'nnd-fr-translator2.firebaseapp.com',
    storageBucket: 'nnd-fr-translator2.appspot.com',
    measurementId: 'G-MG9RL59PPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByAc5hPa2Iv12ZQFLqKmp50spbt1Lrwzk',
    appId: '1:140072372671:android:97ccc02a3e6b43596a390a',
    messagingSenderId: '140072372671',
    projectId: 'nnd-fr-translator2',
    storageBucket: 'nnd-fr-translator2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApOFv9v8VoSQH1OIe-A2xd0hens7vsZxg',
    appId: '1:140072372671:ios:949552bf7b6362576a390a',
    messagingSenderId: '140072372671',
    projectId: 'nnd-fr-translator2',
    storageBucket: 'nnd-fr-translator2.appspot.com',
    iosBundleId: 'com.example.nnbFrTranslator2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApOFv9v8VoSQH1OIe-A2xd0hens7vsZxg',
    appId: '1:140072372671:ios:b4a0a7a18d7bdc136a390a',
    messagingSenderId: '140072372671',
    projectId: 'nnd-fr-translator2',
    storageBucket: 'nnd-fr-translator2.appspot.com',
    iosBundleId: 'com.example.nnbFrTranslator2.RunnerTests',
  );
}
